{% set name = "lux-widget" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lux-widget-{{ version }}.tar.gz
  sha256: f410138514f355c8c9de4f1f8c9534495c5418e9ea1041e8eff03a84b507b60b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - ipywidgets >=7.5.0
    - jupyter
    - notebook >=4.0.0
    - pip
    - python >=3.6
  run:
    - ipywidgets >=7.5.0
    - jupyter
    - notebook >=4.0.0
    - python >=3.6

test:
  imports:
    - luxwidget
    - luxwidget.nbextension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lux-org/lux-widget
  summary: Jupyter Widget for Intelligent Data Discovery
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dorisjlee 
